# Stage 1: Build frontend
FROM node:20-alpine AS frontend-build
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy all frontend source code
COPY . .

# Build the frontend
RUN npm run build




# Stage 2: Nginx to serve frontend
FROM nginx:alpine

# Copy built frontend
COPY --from=frontend-build /app/dist /usr/share/nginx/html

# Copy nginx config (adjust path to root)
COPY ../nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

